### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by benjaminwinger** [arviceblot/bsatool_rs#42]
Are you interested in exposing this as a library as well as a cli tool? It would be helpful for [openmw-cfg](https://gitlab.com/bmwinger/openmw-cfg) to be able to lookup files in the VFS even when they are inside of BSAs.

**Comment by arviceblot** [comment]
Absolutely! It shouldn't be too difficult to separate out a lib and cli bin crate. I will update this issue if I make any major progress on splitting up the project.

**Comment by arviceblot** [comment]
OK, that was pretty easy. The library should now be available on crates.io as `bsatoollib`
